dist: xenial
os: linux
# Released April 2016, Support ended: April 2021
# ruby 2.3.8, 2.4.5 and 2.5.3 (default 2.5.3p105) pre-installed on travis
addons:
  apt:
    packages:
    - net-tools

cache: bundler
language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler ${BUNDLER_VERSION:+-v} ${BUNDLER_VERSION}
  - gem install smarter_bundler
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

jobs:
  fast_finish: true

  include:
    # -------------------------------------
    # Standard
    
    # rails 4.2  Dec, 2014 
    
    - rvm: 2.2.10
      gemfile: test/rails_4.2.gemfile
      env: 
      - RAILS_VERSION=4.2 
      - MIDDLEWARE=no
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    - rvm: 2.1.10
      gemfile: test/rails_4.2.gemfile
      env:
      - RAILS_SERVER=puma
      - RAILS_VERSION=4.2
      - MIDDLEWARE=no
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    # Can't find i18n?? because it can't compile?
    #- rvm: 2.1.2
    #  gemfile: test/rails_4.2.gemfile
    #  env: RAILS_SERVER=passenger RAILS_VERSION=4.2

    - rvm: 2.1.10
      gemfile: test/rails_4.2.gemfile
      env:
      - RAILS_SERVER=thin
      - RAILS_VERSION=4.2
      - MIDDLEWARE=no
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    # No longer supported by travis
    #- rvm: rbx-2.2.6
    #  gemfile: test/rails_4.0.gemfile
    #  env: RAILS_ENV2=development RAILS_VERSION=4.0

    - rvm: 2.1.10
      gemfile: test/rails_4.2.gemfile
      env:
      - RAILS_SERVER=unicorn
      - RAILS_VERSION=4.2
      - MIDDLEWARE=no
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    # Disabled because it takes way too long (40+ mins)
    # Temporary version lock until Bundler >= 1.13.2
    # https://github.com/bundler/bundler/issues/4975
    #- rvm: jruby-19mode
    #  gemfile: test/rails_4.2.gemfile
    #  env: BUNDLER_VERSION=1.12.5 RAILS_VERSION=4.2

    # rails 4.1  April 8, 2014 
    
    - rvm: 2.1.10
      gemfile: test/rails_4.1.gemfile
      env:
      - RAILS_VERSION=4.1
      - MIDDLEWARE=no
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    # rails 4.0
    
    # Required version for latest patch
    # https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html
    - rvm: 1.9.3
      gemfile: test/rails_4.0.gemfile
      env:
      - RAILS_VERSION=4.0
      - MIDDLEWARE=no
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    # -------------------------------------
    # INSTALLED AS MIDDLEWARE
    
    # rails 4.2  Dec, 2014 
    
    - rvm: 2.2.10
      gemfile: test/rails_4.2.gemfile
      env:
      - RAILS_VERSION=4.2
      - MIDDLEWARE=YES
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    - rvm: 2.1.10
      gemfile: test/rails_4.2.gemfile
      env:
      - RAILS_SERVER=puma
      - RAILS_VERSION=4.2
      - MIDDLEWARE=YES
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    # Can't find i18n?? because it can't compile?
    #- rvm: 2.1.2
    #  gemfile: test/rails_4.2.gemfile
    #  env: RAILS_SERVER=passenger RAILS_VERSION=4.2

    - rvm: 2.1.10
      gemfile: test/rails_4.2.gemfile
      env:
      - RAILS_SERVER=thin
      - RAILS_VERSION=4.2
      - MIDDLEWARE=YES
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    # No longer supported by travis

    - rvm: 2.1.10
      gemfile: test/rails_4.2.gemfile
      env:
      - RAILS_SERVER=unicorn
      - RAILS_VERSION=4.2
      - MIDDLEWARE=YES
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    # Disabled because it takes way too long (40+ mins)
    # Temporary version lock until Bundler >= 1.13.2
    # https://github.com/bundler/bundler/issues/4975
    #- rvm: jruby-19mode
    #  gemfile: test/rails_4.2.gemfile
    #  env: BUNDLER_VERSION=1.12.5 RAILS_VERSION=4.2 MIDDLEWARE=YES

    # rails 4.1  April 8, 2014 
    
    # Recommended version for latest patch
    # https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html
    - rvm: 2.1.10
      gemfile: test/rails_4.1.gemfile
      env: 
      - RAILS_VERSION=4.1 
      - MIDDLEWARE=YES
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

    # rails 4.0
    
    - rvm: 1.9.3
      gemfile: test/rails_4.0.gemfile
      env: 
      - RAILS_VERSION=4.0 
      - MIDDLEWARE=YES
      - RUBYGEMS_VERSION=2.7.11
      - BUNDLER_VERSION=1.17.3

