language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler ${BUNDLER_VERSION:+-v} ${BUNDLER_VERSION}
  - gem install smarter_bundler
  - bundle --version
  - bundle ${BUNDLER_VERSION:+_${BUNDLER_VERSION}_} --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

rvm: 
  - 1.9.3

gemfile:
  - test/rails_3.2.gemfile

matrix:
  allow_failures:

  include:
    # rails 3.2 jan 20, 2012 - ruby 1.8.7 or 1.9.2
    
    - rvm: 1.9.3
      gemfile: test/rails_3.2.gemfile
      env: 
      - RAILS_SERVER=puma 
      - RAILS_VERSION=3.2
      - RUBYGEMS_VERSION=1.8.25
      - BUNDLER_VERSION=1.17.3

    - rvm: 1.9.3
      gemfile: test/rails_3.2.gemfile
      env: 
      - RAILS_SERVER=passenger 
      - RAILS_VERSION=3.2
      - RUBYGEMS_VERSION=1.8.25
      - BUNDLER_VERSION=1.17.3

    - rvm: 1.9.3
      gemfile: test/rails_3.2.gemfile
      env: 
      - RAILS_SERVER=thin 
      - RAILS_VERSION=3.2
      - RUBYGEMS_VERSION=1.8.25
      - BUNDLER_VERSION=1.17.3

    - rvm: 1.9.3
      gemfile: test/rails_3.2.gemfile
      env: 
      - RAILS_SERVER=unicorn 
      - RAILS_VERSION=3.2
      - RUBYGEMS_VERSION=1.8.25
      - BUNDLER_VERSION=1.17.3

    # Excluded since it takes way too long!
    #- rvm: jruby-19mode
    #  gemfile: test/rails_3.2.gemfile
    #  env: BUNDLER_VERSION=1.12.5 RAILS_VERSION=3.2

    - rvm: 2.2.0
      gemfile: test/rails_3.2.gemfile
      env: RAILS_VERSION=3.2

    - rvm: 1.9.3
      gemfile: test/rails_3.2.gemfile
      env: 
      - RAILS_VERSION=3.2
      - RUBYGEMS_VERSION=1.8.25
      - BUNDLER_VERSION=1.17.3

    # Excluded since it takes way too long!
    #- rvm: jruby-19mode
    #  gemfile: test/rails_3.2.gemfile
    #  env: BUNDLER_VERSION=1.12.5 RAILS_VERSION=3.2

    # rails 3.1 aug 31, 2011 - ruby 1.8.7 or 1.9.2
    - rvm: 1.9.3
      gemfile: test/rails_3.1.gemfile
      env: 
      - RAILS_VERSION=3.1
      - RUBYGEMS_VERSION=1.8.25
      - BUNDLER_VERSION=1.17.3

