dist: trusty
language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler ${BUNDLER_VERSION:+-v} ${BUNDLER_VERSION}
  - gem install smarter_bundler
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

matrix:
  include:
    - rvm: 1.9.3
      gemfile: test/rails_2.3.gemfile
      env: 
      - RUBYGEMS_VERSION=1.8.25 
      - RAILS_VERSION=2.3
      - BUNDLER_VERSION=1.17.3

    - rvm: 1.9.3
      gemfile: test/rails_2.3_lts.gemfile
      env:
      - RUBYGEMS_VERSION=1.8.25
      - RAILS_VERSION=2.3
      - BUNDLER_VERSION=1.17.3

    - rvm: 2.7
      gemfile: test/rails_2.3_lts.gemfile
      env:
      #- RUBYGEMS_VERSION=1.8.25
      - RAILS_VERSION=2.3
      #- BUNDLER_VERSION=1.17.3

